services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: taxi
      POSTGRES_PASSWORD: taxi
      POSTGRES_DB: taxi_dw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/data
volumes:
  pgdata:
